### ISSUE TITLE
Bytes remaining to read from async njs handler

### ISSUE THREAD

**Issue by enp** [nginx/njs#831]
### Bytes remaining to read from async njs handler

I can't receive full response body from async njs handler with `ngx.fetch` in it:

```
async function content(request) {
  try {
    const url = "https://raw.githubusercontent.com/Schlumberger/hackathon/refs/heads/master/backend/dataset/data-large.csv"
    const data = await ngx.fetch(url, { verify: false, max_response_body_size: 1000000000 })
    const text = await data.text()
    request.return(200, text)
  } catch(error) {
    request.return(500, error)
  }
}

export default { content }
```

```
$ curl -s -v http://localhost
* Host localhost:80 was resolved.
* IPv4: 127.0.0.1
*   Trying 127.0.0.1:80...
* Connected to localhost (127.0.0.1) port 80
> GET / HTTP/1.1
> Host: localhost
> User-Agent: curl/8.7.1
> Accept: */*
> ^M
* Request completely sent off
< HTTP/1.1 200 OK
< Server: nginx/1.27.3
< Date: Wed, 25 Dec 2024 13:09:15 GMT
< Content-Type: text/plain
< Content-Length: 37923268
< Connection: keep-alive
< 
{ [65382 bytes data]
...
* transfer closed with 35826270 bytes remaining to read
* Closing connection
curl: (18) transfer closed with 35826270 bytes remaining to read
```

After replacing `request.return(200, text)` by  `request.return(200, text.length)` all works as expected - so, problem is not timeout-related

Returning huge hardcoded (or created by loop) text without `ngx.fetch` is also not a problem

### To reproduce

Just run `./nginx.sh` with all files in [attached archive](https://github.com/user-attachments/files/18246133/nginx.zip)

### Additional context

This is simple case, real case includes more than one fetch with parsing output - so `proxy_pass` is not an option

**Comment by enp** [comment]
No success even with subrequest and proxy_pass:

```
location / {
  js_content script.content;
}
location /data-large {
  internal;
  proxy_pass https://raw.githubusercontent.com/Schlumberger/hackathon/refs/heads/master/backend/dataset/data-large.csv;
}
```
```
const data = await request.subrequest('/data-large');
request.return(200, data.responseText)
```

Same result for requesting `/` and `/large-data`:

```
curl: (52) Empty reply from server
```
```
2024/12/26 17:58:37 [error] 29#29: *3 too big subrequest response: 37923268 while sending to client, client: 127.0.0.1, server: , request: "GET /large-data HTTP/1.1", subrequest: "/data-large", upstream: "https://185.199.110.133:443/Schlumberger/hackathon/refs/heads/master/backend/dataset/data-large.csv", host: "localhost"
127.0.0.1 - - [26/Dec/2024:17:58:37 +0000] "GET /large-data HTTP/1.1" 000 0 "-" "curl/8.11.1"
2024/12/26 17:58:37 [error] 29#29: *3 pending events while closing request, client: 127.0.0.1, server: 0.0.0.0:80
````

**Comment by xeioex** [comment]
Hi @enp,

For too big subrequest try to increase the buffer size with [subrequest_output_buffer_size](https://nginx.org/en/docs/http/ngx_http_core_module.html#subrequest_output_buffer_size).

**Comment by enp** [comment]
Hi @xeioex,

With `subrequest_output_buffer_size 250M` (much more than file size) I received something like above with `ngx.fetch`:

```
curl: (18) end of response with 35826270 bytes missing
```
```
127.0.0.1 - - [26/Dec/2024:19:10:10 +0000] "GET / HTTP/1.1" 200 2096998 "-" "curl/8.11.1"
```

Interesting thing: 35826270 (from curl) + 2096998 (from access log) = 37923268 (file size on raw.githubusercontent.com as reported in content-length header by direct request)

**Comment by xeioex** [comment]
Hi @enp,

 [subrequest_output_buffer_size](https://nginx.org/en/docs/http/ngx_http_core_module.html#subrequest_output_buffer_size) is only applicable for subrequest calls.

Does the subrequest version works for you with large enough `subrequest_output_buffer_size`?

**Comment by xeioex** [comment]
Hi @enp,

What njs version are you using? You are hitting the same issue reported in https://github.com/nginx/njs/issues/825.
The issue is fixed since 0.8.8.

**Comment by enp** [comment]
Hi @xeioex,

Please see [attached example](https://github.com/user-attachments/files/18258195/nginx.zip) with all cases

Version with `ngx.fetch` closes connection before transmitting all bytes:

```
$ curl http://localhost/fetch
...
curl: (18) end of response with 35826270 bytes missing
```
```
127.0.0.1 - - [27/Dec/2024:06:35:40 +0000] "GET /fetch HTTP/1.1" 200 2096998 "-" "curl/8.11.1"
```

Version with `subrequest` + large enough `subrequest_output_buffer_size` does the same:

```
$ curl http://localhost/subrequest
...
curl: (18) end of response with 35826270 bytes missing
```
```
127.0.0.1 - - [27/Dec/2024:06:38:39 +0000] "GET /subrequest HTTP/1.1" 200 2096998 "-" "curl/8.11.1"
```

Versions with generation large text (`/local` localtion) and `proxy_pass` (`/subrequest-data` location) returns all bytes:

```
127.0.0.1 - - [27/Dec/2024:06:43:34 +0000] "GET /subrequest-data HTTP/1.1" 200 37923268 "-" "curl/8.11.1"
127.0.0.1 - - [27/Dec/2024:06:52:17 +0000] "GET /local HTTP/1.1" 200 37923268 "-" "curl/8.11.1"
```

So, #825 not looks the same issue

As for version - I'm using latest nginx docker image:

```
$ docker images
REPOSITORY   TAG       IMAGE ID       CREATED       SIZE
nginx        latest    f876bfc1cc63   4 weeks ago   192MB

$ docker ps
CONTAINER ID   IMAGE     COMMAND                  CREATED          STATUS          PORTS     NAMES
e668f58e41b6   nginx     "/docker-entrypoint.…"   47 seconds ago   Up 47 seconds             nervous_tesla

$ docker exec e668f58e41b6 nginx -V
nginx version: nginx/1.27.3
built by gcc 12.2.0 (Debian 12.2.0-14) 
built with OpenSSL 3.0.11 19 Sep 2023 (running with OpenSSL 3.0.15 3 Sep 2024)
TLS SNI support enabled
configure arguments: --prefix=/etc/nginx --sbin-path=/usr/sbin/nginx --modules-path=/usr/lib/nginx/modules --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --pid-path=/var/run/nginx.pid --lock-path=/var/run/nginx.lock --http-client-body-temp-path=/var/cache/nginx/client_temp --http-proxy-temp-path=/var/cache/nginx/proxy_temp --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp --http-scgi-temp-path=/var/cache/nginx/scgi_temp --user=nginx --group=nginx --with-compat --with-file-aio --with-threads --with-http_addition_module --with-http_auth_request_module --with-http_dav_module --with-http_flv_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_mp4_module --with-http_random_index_module --with-http_realip_module --with-http_secure_link_module --with-http_slice_module --with-http_ssl_module --with-http_stub_status_module --with-http_sub_module --with-http_v2_module --with-http_v3_module --with-mail --with-mail_ssl_module --with-stream --with-stream_realip_module --with-stream_ssl_module --with-stream_ssl_preread_module --with-cc-opt='-g -O2 -ffile-prefix-map=/data/builder/debuild/nginx-1.27.3/debian/debuild-base/nginx-1.27.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fPIC' --with-ld-opt='-Wl,-z,relro -Wl,-z,now -Wl,--as-needed -pie'
```

How to know (and change) njs version?

**Comment by xeioex** [comment]
@enp,

Yes, I checked your fetch example. In my test the problem goes away starting from 0.8.8 version.

To see the version, `function version (r) {r.return(200, njs.version)}`. Probably the docker image is not updated yet.

**Comment by thresheek** [comment]
Hey @enp 

I've just pushed updates to njs 0.8.8 to nginx docker images sources;  would appreciate if you could build and test those:

```
git clone https://github.com/nginxinc/docker-nginx
cd docker-nginx/mainline/debian
docker build -t nginx:latest .
```

I plan to get those built & published to the Docker Library too, but that's going to take some time.

**Comment by enp** [comment]
@thresheek @xeioex thanks, it works!

**Comment by enp** [comment]
@thresheek where new image should be published?

https://hub.docker.com/layers/library/nginx/stable-alpine/images/sha256-c8fac17ccd9d570a6a5d358fca9d295895333ce1498f45c15ba5dfe88da7dfab looks as latest alpine-based image, but still not contains updated njs version

**Comment by thresheek** [comment]
Hey @enp, we typically update njs when a new nginx release is out.  No ETA for that yet.

**Comment by enp** [comment]
Hi @thresheek thank you for answer

But I see images published less than 24 hours ago in https://hub.docker.com/_/nginx/tags (only alpine-based images, not debian-based)

Why these images are published? Maybe release process for docker images is described somewhere?
